all:	firstPassword secondPassword
firstPassword: 
	g++ firstPasswordPhilosophy.cpp -o testPasswordPhilosophy.out
secondPassword: 
	g++ secondPasswordPhilosophy.cpp -o passwordPhilosophy.out
clean:
	rm *.out
